### ISSUE TITLE
Final json string is not printed for LeCaR 

### ISSUE THREAD

**Issue by lynnliu030** [sunnyszy/lrb#8]
Hi,
    When I was trying to run LeCaR, for example, by using this command `sudo docker run -it -v ~/lrb/trace:/trace sunnyszy/webcachesim wiki2018.tr LeCaR 549755813888 > wiki18_LeCaR_512GB.txt`, in the txt I did not see the final result json string printed. Instead I just have 
![image](https://user-images.githubusercontent.com/39693493/112569188-b1675880-8db1-11eb-99fb-df26d136282d.png)
And it got stuck there. I was wondering why this would happen?

**Comment by sunnyszy** [comment]
Hi @lynnliu030 ,

Thanks for reporting this problem. I replicated the bug and the problem you saw is because the simulator has a memory bug and froze in the simulation. 

I fixed it in https://github.com/sunnyszy/lrb/commit/161ba3dfa81ba11a0d3c11fe44ceec001774483d. Please update your docker image to the latest version and have a try.

**Comment by lynnliu030** [comment]
@sunnyszy Thanks!
